'use client';
// NeoStampa Job Ticket XML preview — built against the actual Inèdit neoRipEngine
// 4.23.0 spec (uploaded by Nick 2026-06-23). The XML produced here matches the
// real Job/Sources/Layout/Page/Objects/Transformations/Output/Notifications shape,
// with the RapportInfo element textile printers use for pattern repeat and the
// printingStart/End/Abort notification URLs that point at a Helm webhook so RIP
// events flow back into the database. Generated client-side from PR + RipJob data.
import { useEffect, useState } from 'react';
import { X, Download, Copy, Check } from 'lucide-react';

export type XmlJobInput = {
  prNumber: string;
  prId: number;
  externalJobName: string;
  fabricOutputPayload: string | null;
  customerName: string;
  designName: string | null;
  plantNumber: string | null;
  colorwayName: string | null;
  fabricName: string | null;
  fabricWidthIn: number | null;     // physical fabric width
  printWidthIn: number | null;      // printable area
  printedYards: number | null;      // planned / printed yardage
  printerName: string;
  inkSet: string;                   // 'Pigment' | 'Fiber Reactive' | 'Dye Sublimation' | 'Latex'
  iccProfileFile: string | null;    // computed from printer × fabric × ink set
  hotFolderPath: string;
  agentName: string;
};

// Build the Inèdit job ticket XML from a PR's data
export function buildNeoStampaXml(input: XmlJobInput): string {
  const slug = (s: string) => s.replace(/[^A-Z0-9]+/gi, '-').replace(/^-|-$/g, '');
  const customerSlug = slug((input.customerName ?? 'CUSTOMER').toLowerCase());
  const designSlug = slug((input.designName ?? 'design').toLowerCase());
  const colorwaySlug = slug((input.colorwayName ?? 'default').toLowerCase());

  // Source paths follow ADT's NAS convention
  const artworkPath = `\\\\adt-nas\\artwork\\${customerSlug}\\${input.plantNumber ?? designSlug}\\${designSlug}_${colorwaySlug}_production.tiff`;
  const iccPath = input.iccProfileFile
    ? `\\\\adt-nas\\profiles\\${input.iccProfileFile}`
    : `\\\\adt-nas\\profiles\\${slug(input.printerName)}_${slug(input.fabricName ?? 'pfp')}_${slug(input.inkSet)}.icc`;

  // Output color space per ink set
  const outputSpace = input.inkSet.toLowerCase().includes('pigment') ? 'CMYK'
    : input.inkSet.toLowerCase().includes('reactive') ? 'CMYK'
    : input.inkSet.toLowerCase().includes('sub') ? 'CMYK'
    : 'CMYK';

  // Dimensions — convert inches to mm for the XML (Inèdit accepts both, mm is common)
  const pageWidthMm = input.printWidthIn ? (input.printWidthIn * 25.4).toFixed(2) : '1422.40';
  // Use printed yards converted to mm for page height (1 yd = 914.4 mm)
  const pageHeightMm = input.printedYards ? (input.printedYards * 914.4).toFixed(2) : '4572.00';

  // Helm webhook base URL for notifications
  const webhookBase = `https://helm.adt.com/api/rip-events`;
  const job = encodeURIComponent(input.externalJobName);

  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
  Inèdit neoRipEngine job ticket · generated by Helm for ${input.prNumber}
  External job name: ${input.externalJobName}
  Spec reference: 4.23.0 neoRipEngine · Sources/Layout/Page/Objects/Output/Notifications
-->
<Job>
  <Sources>
    <!-- Source 0: customer artwork (NAS) -->
    <Source Id="0" URL="${artworkPath}" autoResolution="true"/>
    <!-- Source 1: printer × fabric × ink-set ICC profile -->
    <Source Id="1" URL="${iccPath}"/>
  </Sources>

  <Layout>
    <Page Id="0" width="${pageWidthMm} mm" height="${pageHeightMm} mm">
      <RapportInfo direction="V" fraction_high="1" fraction_low="2"/>
      <Objects>
        <Object Id="0" SourceID="0"
                left="0 mm" top="0 mm"
                width="${pageWidthMm} mm" height="${pageHeightMm} mm"
                MaintainAspectRatio="true"
                repeat="rapport"
                interpolationMethod="bicubic">
          <Transformations>
            <!-- Convert artwork to printer ICC profile -->
            <ConvertProfile CMM="lcms" SourceID="1" intent="relative" blackPoint="yes" quality="hq"/>
          </Transformations>
        </Object>
      </Objects>
    </Page>
  </Layout>

  <Output>
    <WorkingProfile CMM="lcms"/>
    <OutputProfile Filename="${iccPath}" Space="${outputSpace}" Intent="relative"/>
    <Space>${outputSpace}</Space>
    <BitsPerComponent>16</BitsPerComponent>
    <ResolutionX>720</ResolutionX>
    <ResolutionY>720</ResolutionY>
    <ResolutionUnits>dpi</ResolutionUnits>
    <OutputEncodingOptions>
      <CompressionType>lzw</CompressionType>
      <ByteOrder>IBM PC</ByteOrder>
    </OutputEncodingOptions>
    <OutputFormat>tif</OutputFormat>
    <OutputFilename>${input.externalJobName}</OutputFilename>
    <Copies>1</Copies>
  </Output>

  <!-- Inèdit notification webhooks → Helm RIP event ingestion
       (printingStart/End/Abort/Message URLs per neoRipEngine 4.23.0 spec, page 85) -->
  <Notifications>
    <printingStart URL="${webhookBase}?event=print_started&amp;job=${job}&amp;pr=${input.prNumber}&amp;agent=${encodeURIComponent(input.agentName)}"/>
    <printingEnd   URL="${webhookBase}?event=print_completed_software&amp;job=${job}&amp;pr=${input.prNumber}&amp;agent=${encodeURIComponent(input.agentName)}"/>
    <printingAbort URL="${webhookBase}?event=print_aborted&amp;job=${job}&amp;pr=${input.prNumber}&amp;agent=${encodeURIComponent(input.agentName)}"/>
    <printingMessage URL="${webhookBase}?event=message&amp;job=${job}&amp;pr=${input.prNumber}"/>
  </Notifications>
</Job>
`;
}

export function NeoStampaXmlPreview({ input, onClose }: { input: XmlJobInput; onClose: () => void }) {
  const [copied, setCopied] = useState(false);
  const xml = buildNeoStampaXml(input);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose(); };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [onClose]);

  function copy() {
    navigator.clipboard.writeText(xml);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  function download() {
    const blob = new Blob([xml], { type: 'application/xml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${input.externalJobName}.xml`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4 overflow-y-auto" onClick={onClose}>
      <div className="bg-white rounded-lg shadow-2xl max-w-5xl w-full my-8" onClick={(e) => e.stopPropagation()}>
        <div className="flex items-center justify-between px-4 py-2.5 border-b border-gray-200 bg-gray-50 rounded-t-lg">
          <div>
            <div className="text-sm font-semibold text-navy-900">NeoStampa Job Ticket · XML Preview</div>
            <div className="text-[10px] text-gray-500 font-mono">{input.externalJobName}.xml</div>
          </div>
          <div className="flex gap-2">
            <button onClick={copy} className="inline-flex items-center gap-1 px-2.5 py-1 text-xs font-semibold text-navy-700 bg-white border border-gray-300 hover:bg-gray-50 rounded">
              {copied ? <><Check className="w-3.5 h-3.5" />Copied</> : <><Copy className="w-3.5 h-3.5" />Copy</>}
            </button>
            <button onClick={download} className="inline-flex items-center gap-1 px-2.5 py-1 text-xs font-semibold text-white bg-navy-700 hover:bg-navy-900 rounded">
              <Download className="w-3.5 h-3.5" />Download .xml
            </button>
            <button onClick={onClose} className="inline-flex items-center gap-1 px-2.5 py-1 text-xs font-semibold text-gray-600 hover:bg-gray-100 rounded">
              <X className="w-3.5 h-3.5" />Close
            </button>
          </div>
        </div>

        <div className="p-4 max-h-[70vh] overflow-y-auto">
          <pre className="text-[11px] leading-5 font-mono text-gray-800 bg-gray-50 border border-gray-200 rounded p-4 whitespace-pre">
            {xml}
          </pre>
          <div className="mt-3 text-[10px] text-gray-500 italic space-y-1.5">
            <div>
              Generated against Inèdit neoRipEngine spec v4.23.0. Notification URLs would be POSTed by the agent when print events fire — Helm ingests these at <code className="font-mono">/api/rip-events</code> and writes <code className="font-mono">rip_job_events</code> rows. The composite/.prn file is produced upstream by the Compositing Engine and dropped into the hot folder at <code className="font-mono break-all">{input.hotFolderPath}</code>.
            </div>
            <div>
              <strong>Helm-originated only.</strong> Canvas-originated jobs (started in NeoStampa Canvas by a colorist, not minted by Helm) don&apos;t carry this XML — they get observed by the agent via log-tail and land in the Reconciliation Queue on <code className="font-mono">/printer-queue</code> until an operator binds them to a PR.
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
